### ISSUE TITLE
check support for 1.0.0

### ISSUE THREAD

**Issue by xackery** [appleboy/drone-discord#11]
seems right now that 1.0.0 support isn't functioning, I had to set up drone.yml with
```
---
kind: pipeline
name: default
  
steps:
- name: discord
  pull: default
  image: appleboy/drone-discord
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN: 
      from_secret: discord_webhook_token
  when:
    event: [ push, tag, pull_request ]
    status: [ changed, failure, success ]
  message: >
    {{#success build.status}}
      build {{repo.name}} {{build.branch}} {{build.number}} succeeded. Good job.
    {{else}}
      build {{repo.name}} {{build.branch}} {{build.number}} failed. Fix me please. {{build.link}}
    {{/success}}
```

but all I get is:
<img width="322" alt="screen shot 2018-11-11 at 8 37 18 pm" src="https://user-images.githubusercontent.com/845670/48327081-9dac6480-e5f1-11e8-89d1-9423d06267bf.png">

**Comment by bradrydzewski** [comment]
your syntax needs to be adjusted for 1.0

```
kind: pipeline

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: ...
```
