### ISSUE TITLE
no message on discord

### ISSUE THREAD

**Issue by ScrumpyJack** [appleboy/drone-discord#16]
i'm not getting a message on discord with the 1.0.0 drone yaml syntax
have I got this right?

```
kind: pipeline
name: default

steps:

- name: notify
  image: appleboy/drone-discord:1.0.0
  pull: always
  settings:
    webhook_id:
      from_sercet: discord_webhook_id
    webhook_token:
      from_sercet: discord_webhook_token
    message: testing123
```
