### ISSUE TITLE
Helper datetime failing after fixing #21

### ISSUE THREAD

**Issue by pztrn** [appleboy/drone-discord#22]
Just launched my pipeline (https://sources.dev.pztrn.name/fastpastebin/fastpastebin/src/branch/master/.drone.yml) and encounter error:

```
Evaluation error: Helper datetime called with argument 0 with type int64 but it should be float64
--
```

It was working before fixing #21

**Comment by pztrn** [comment]
Hey, any updates on that?

**Comment by jimmybrancaccio** [comment]
This looks to still be an issue, however I am getting a different error:

```
2020/02/25 01:02:25 Evaluation error: Helper 'datetime' called with wrong number of arguments, needed 3 but got 1
```

**Comment by siperialainen** [comment]
Faced the same problem.

**Comment by appleboy** [comment]
correct example:

```yaml
- name: discord
  pull: always
  image: appleboy/drone-discord
  settings:
    message: "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"Asia/Taipei\"}} \n\n ✅ finished: {{datetime build.finished \"2006/01/02 15:04\" \"Asia/Taipei\"}} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"Asia/Taipei\"}} \n\n ✅ finished: {{datetime build.finished \"2006/01/02 15:04\" \"Asia/Taipei\"}}{{/success}}\n"
```

See `{{datetime build.started "2006/01/02 15:04" "Asia/Taipei"}}`

format: `2006/01/02 15:04`
time zone: `Asia/Taipei`

https://github.com/appleboy/drone-discord/blob/cb122520bda0c2f26fc4b061f6f5a7e9f4c2ff59/.drone.yml#L345-L354

![Screen Shot 2020-03-26 at 11 56 32 PM](https://user-images.githubusercontent.com/21979/77667667-7a534100-6fbd-11ea-9921-0f51c32846df.png)

**Comment by jimmybrancaccio** [comment]
Apologies for commenting on the closed issue, but it looks like the timezone doesn't work. In your screenshot it shows 11:51pm but the started and ending times don't match up. Unless if your Discord client and Drone server are in different timezones?

That said, I can't get it working either, it seems to always default to UTC time. I can open a new issue if you'd prefer to address this.

**Edit:** This is actually probably an issue with Drone itself, not the plugin.

**Comment by Selfmade-RuLeZ** [comment]
![droneDiscord](https://user-images.githubusercontent.com/53468564/88224160-dd519d80-cc68-11ea-95da-a66081155049.png)

Is this still issue still present? Or is the duration fault a Drone.io issue? 

BTW: Thank your for your nice plugin!

**Comment by jimmybrancaccio** [comment]
@Selfmade-RuLeZ This is just how Drone works. `build.finished` returns `now`. So it will basically be the same value as `build.started`. So when you compare them, it'll be the same number, thus 0s as a duration.

**Comment by Selfmade-RuLeZ** [comment]
Is this a missunderstanding? I mean, `build.started` should return, when the build has started, in my case at 20:04. So the duration has to be 6 minutes or am I wrong? 
This is my message:
```
message: "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"02.01.2006 15:04\" \"Europe/Berlin\"}} \n\n ✅ finished: {{datetime build.finished \"02.01.2006 15:04\" \"Europe/Berlin\"}} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"02.01.2006 15:04\" \"Europe/Berlin\"}} \n\n ✅ finished: {{datetime build.finished \"02.01.2006 15:04\" \"Europe/Berlin\"}}{{/success}}\n"
```

**Comment by appleboy** [comment]
Please try the latest version: https://github.com/appleboy/drone-discord/releases/tag/v1.2.6

**Comment by Selfmade-RuLeZ** [comment]
Your since-function is working fine now. But the error I mean is still present and I think it's a fault from Drone.io or my missunderstanding.
The environmentvariables DRONE_BUILD_STARTED and _FINSIHED of the Discord-Drone-Docker container are both setted 
with 1595488993 in my last example. Is it a reference to the drone-discord build?

This is my complete pipeline if it helps: 
```
---
kind: pipeline
type: docker
name: frontend

steps:
  - name: test frontend
    image: node
    commands:
      - cd frontend
      - npm install
      - npm test

  - name: notify over discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{uppercasefirst commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{since build.started}} \n\n ✅ started: {{datetime build.started \"02.01.2006 15:04\" \"Europe/Berlin\"}} \n\n ✅ finished: {{datetime build.finished \"02.01.2006 15:04\" \"Europe/Berlin\"}} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{uppercasefirst commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{since build.started}} \n\n ✅ started: {{datetime build.started \"02.01.2006 15:04\" \"Europe/Berlin\"}} \n\n ✅ finished: {{datetime build.finished \"02.01.2006 15:04\" \"Europe/Berlin\"}}{{/success}}\n"
```
