### ISSUE TITLE
secrets not working as documented

### ISSUE THREAD

**Issue by fgierlinger** [appleboy/drone-discord#28]
I found a way to export the discord_id and discord_token to secrets, but not as documented. My way:

```
   - name: notification on failure
      image: appleboy/drone-discord
      settings:
          webhook_id:
              from_secret: discord_webhook_id
          webhook_token:
              from_secret: discord_webhook_token
```

The documentation says, that the parameter `secrets` should be used, but there was no way that I managed to make it work that way.

```
   - name: notification on failure
      image: appleboy/drone-discord
      settings:
          secrets: [discord_webhook_id, discord_webhook_token]
```

Am I doing something wrong, or is an update of the documentation required?
