### ISSUE TITLE
Plugin seems to no longer be working even with super barebones pipeline

### ISSUE THREAD

**Issue by q23407u892f** [appleboy/drone-discord#40]
I want to believe im doing it wrong, but even with the most barebones settings, this is not sending notifications. I have verified my webhook url is correct by running a curl command which is sending notifications to discord

here is my bare bones .drone.yml file which is not posting to discord

```yaml
kind: pipeline
type: docker
name: Testing droneXdiscord integration

steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: "Testing from drone pipeline"

```
For reference, this curl command  (using the same exact webhook id and token) works

```
curl --json '{"username": "Drone CI", "avatar_url": "https://miro.medium.com/v2/resize:fit:1358/0*AqO_2lNemh_Fl9Gm.png","content": "Testing from curl"}' https://discord.com/api/webhooks/<webhook_id>/<webhook_token>
```

And just for good measure, tried running the binary by itself which  _DOES_ work

```
./drone-discord -webhook-id=<id> -webhook-token=<token> -message="test"
```

**Comment by glitch-bane** [comment]
I _believe_ you'll need to set the username parameter as well.  `username: user_example`.

Maybe along the lines of:

```
kind: pipeline
type: docker
name: Testing droneXdiscord integration

steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: "Testing from drone pipeline"
    username: test
  when:
    status:
      - success
      - changed
      - failure
```
