### ISSUE TITLE
Intermittent X509 Certificate Signed by Unknown Authority

### ISSUE THREAD

**Issue by mateushfmag** [appleboy/drone-discord#53]
Hello!
Well, i've been using this plugin in a drone ci kubernetes environment and this error keeps occuring.
Sometimes the pipeline just fails for this reason showed below
![image](https://github.com/appleboy/drone-discord/assets/47339005/1c8cfa90-4aed-49be-8a6c-644c00c5bd69)

The only thing this step does is send a message in my discord channel through a webhook. The .drone.yml is here:
```yml
kind: pipeline
type: kubernetes
name: pr-open
trigger:
  event:
    - pull_request
  action:
    - opened

steps:
  - name: discord
    pull: always
    image: appleboy/drone-discord
    settings:
      message: "## New PR 🥳🚀 \n [${DRONE_PULL_REQUEST_TITLE}](${DRONE_REPO_LINK}/pull/${DRONE_PULL_REQUEST})"
      webhook_id: '<my-discord-id>'
      webhook_token: '<my-discord-token>'
```
Did this happen to anyone else? Does someone have a clue in how to solve this?
Just a reminder, the error is intermittent... so after a few restarts, it works!
